"""
Pluggable LLM client — supports Mock, OpenAI, Ollama, Gemini, Anthropic.
Provider is selected via LLM_PROVIDER env var.
"""
from __future__ import annotations
import json
import random
from typing import Any

from core.config import settings


class BaseLLMClient:
    async def complete(self, prompt: str) -> dict[str, Any]:
        raise NotImplementedError


class MockLLMClient(BaseLLMClient):
    """Deterministic mock for development/testing."""

    MOCK_RESPONSES = [
        {
            "reasoning": (
                "Based on the evidence reviewed, multiple high-risk entities have been identified. "
                "The transaction patterns exhibit significant deviation from baseline behavior, "
                "with several accounts showing velocity anomalies and unusual cross-border transfers. "
                "The email chain contains indicators of social engineering, including domain spoofing "
                "and mismatched Reply-To addresses."
            ),
            "hypothesis": "Coordinated fraud ring operating across at least 3 jurisdictions with inside knowledge of target organization.",
            "confidence": "medium-high",
            "next_steps": [
                "Subpoena financial records for accounts flagged by Isolation Forest",
                "Cross-reference IP addresses with known threat intelligence feeds",
                "Interview account holders for transactions >$50,000",
                "Engage international liaison for cross-border entities",
            ],
            "content": "Investigation summary generated by ForensIQ AI (mock mode).",
            "summary": "High-risk coordinated fraud pattern detected across evidence artifacts.",
        }
    ]

    async def complete(self, prompt: str) -> dict[str, Any]:
        return random.choice(self.MOCK_RESPONSES)


class OpenAILLMClient(BaseLLMClient):
    def __init__(self):
        from openai import AsyncOpenAI
        self._client = AsyncOpenAI(api_key=settings.LLM_API_KEY)

    async def complete(self, prompt: str) -> dict[str, Any]:
        response = await self._client.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are ForensIQ, an AI forensic investigator. "
                        "Analyze the provided evidence and respond in JSON with keys: "
                        "reasoning, hypothesis, confidence, next_steps (list), content, summary."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            response_format={"type": "json_object"},
            temperature=0.3,
        )
        text = response.choices[0].message.content or "{}"
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return {"content": text, "reasoning": text}


class OllamaLLMClient(BaseLLMClient):
    async def complete(self, prompt: str) -> dict[str, Any]:
        import httpx
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": settings.LLM_MODEL or "llama3.2",
                    "prompt": (
                        f"You are ForensIQ, an AI forensic investigator. "
                        f"Respond in JSON with keys: reasoning, hypothesis, confidence, next_steps, content, summary.\n\n{prompt}"
                    ),
                    "format": "json",
                    "stream": False,
                },
            )
            data = resp.json()
            text = data.get("response", "{}")
            try:
                return json.loads(text)
            except json.JSONDecodeError:
                return {"content": text, "reasoning": text}


class AnthropicLLMClient(BaseLLMClient):
    def __init__(self):
        import anthropic
        self._client = anthropic.AsyncAnthropic(api_key=settings.LLM_API_KEY)

    async def complete(self, prompt: str) -> dict[str, Any]:
        message = await self._client.messages.create(
            model=settings.LLM_MODEL or "claude-3-5-sonnet-20241022",
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
            system=(
                "You are ForensIQ, an AI forensic investigator. "
                "Always respond in valid JSON with keys: reasoning, hypothesis, confidence, next_steps, content, summary."
            ),
        )
        text = message.content[0].text if message.content else "{}"
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return {"content": text, "reasoning": text}


_CLIENT: BaseLLMClient | None = None


def get_llm_client() -> BaseLLMClient:
    global _CLIENT
    if _CLIENT is not None:
        return _CLIENT

    provider = settings.LLM_PROVIDER.lower()
    if provider == "openai":
        _CLIENT = OpenAILLMClient()
    elif provider == "ollama":
        _CLIENT = OllamaLLMClient()
    elif provider == "anthropic":
        _CLIENT = AnthropicLLMClient()
    else:
        _CLIENT = MockLLMClient()

    return _CLIENT
