import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowLeft, FileText, Plus, Loader2, RefreshCw, Download } from 'lucide-react'
import { reportsApi } from '../lib/api'
import ReportDownloader from '../components/ReportDownloader'

export default function ReportsView() {
  const { id: caseId } = useParams<{ id: string }>()
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [options, setOptions] = useState({
    include_graph: true,
    include_anomalies: true,
    include_custody: true,
    ai_narrative: true,
    generated_by: 'analyst',
  })

  const load = async () => {
    setLoading(true)
    try {
      const res = await reportsApi.list(caseId!)
      setReports(res.data)
    } catch {
      setReports([])
    } finally {
      setLoading(false)
    }
  }

  const generate = async () => {
    setGenerating(true)
    try {
      await reportsApi.generate(caseId!, options)
      await load()
    } catch {
      alert('Report generation failed — check backend connection')
    } finally {
      setGenerating(false)
    }
  }

  useEffect(() => { load() }, [caseId])

  return (
    <div className="space-y-5 max-w-4xl mx-auto animate-slide-up">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link to={`/cases/${caseId}`} className="btn-ghost p-2">
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <FileText className="w-5 h-5 text-brand-400" />
          <div>
            <h2 className="font-bold text-white">Investigation Reports</h2>
            <p className="text-xs text-slate-500">{reports.length} report{reports.length !== 1 ? 's' : ''} generated</p>
          </div>
        </div>
        <div className="flex gap-2">
          <button onClick={load} className="btn-ghost flex items-center gap-2 text-sm">
            <RefreshCw className="w-4 h-4" />
          </button>
          <button onClick={generate} disabled={generating} className="btn-brand flex items-center gap-2">
            {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
      </div>

      {/* Options */}
      <div className="glass p-5">
        <h3 className="section-title mb-4">Report Options</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { key: 'include_graph', label: 'Include Graph' },
            { key: 'include_anomalies', label: 'Anomaly Data' },
            { key: 'include_custody', label: 'Custody Chain' },
            { key: 'ai_narrative', label: 'AI Narrative' },
          ].map(({ key, label }) => (
            <label key={key} className="flex items-center gap-2 cursor-pointer group">
              <div
                onClick={() => setOptions(o => ({ ...o, [key]: !o[key as keyof typeof o] }))}
                className={`w-5 h-5 rounded border flex items-center justify-center transition-all cursor-pointer ${
                  options[key as keyof typeof options]
                    ? 'bg-brand-600 border-brand-600'
                    : 'bg-slate-800 border-slate-600 group-hover:border-slate-500'
                }`}
              >
                {options[key as keyof typeof options] && (
                  <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                )}
              </div>
              <span className="text-sm text-slate-300 select-none">{label}</span>
            </label>
          ))}
        </div>
        <div className="mt-4">
          <label className="text-xs text-slate-500 block mb-1.5">Generated By</label>
          <input
            type="text"
            value={options.generated_by}
            onChange={e => setOptions(o => ({ ...o, generated_by: e.target.value }))}
            className="form-input text-sm max-w-xs"
            placeholder="Analyst name..."
          />
        </div>
      </div>

      {/* Report info */}
      <div className="glass p-4 border-l-4 border-amber-500">
        <p className="text-sm text-slate-300">
          Each generation creates <strong className="text-white">both PDF and JSON</strong> reports.
          Reports are cryptographically hashed (SHA-256) and stored with metadata for audit purposes.
        </p>
      </div>

      {/* Reports list */}
      {loading ? (
        <div className="flex justify-center py-8">
          <div className="w-6 h-6 border-2 border-brand-500 border-t-transparent rounded-full animate-spin" />
        </div>
      ) : (
        <ReportDownloader
          reports={reports}
          onDelete={id => setReports(r => r.filter(rep => rep.id !== id))}
        />
      )}
    </div>
  )
}
